Repository embroider-build/app-blueprint, pull requests merged in 2024-11, with the labels that each got.

#104 Remove ember-cli-inject-live-reload dependency
  index.js
Labels: enhancement

#110 fix upstream issue with typescript-eslint
  index.js
Labels: bug

#107 Update ember cli to 6.0
  package.json
  pnpm-lock.yaml
Labels: enhancement

#112 delete TS file in JS fixture
  tests/fixture/app/router.ts
Labels: internal

#74 add a test to verify generators are still working
  index.js
  tests/default.test.mjs
Labels: internal

#116 bump @ember/test-helpers and stop ember-qunit from using requirejs
  files-override/js/tests/test-helper.js
  files-override/ts/tests/test-helper.ts
  index.js
Labels: enhancement

#117 Stick to vite v5 for now
  index.js
Labels: bug

#119 Remove webpack from dependencies
  index.js
Labels: enhancement
