Repository embroider-build/app-blueprint, pull requests merged in 2024-09, with the labels that each got.

#58 Fixes app import paths in index.html
  files-override/app/index.html
Labels: bug

#60 Add /tmp/ to files-override/.gitignore
  files-override/.gitignore
Labels: bug

#62 move the index.html into the root of the blueprint
  files/index.html
  index.js
  tests/default.test.mjs
Labels: enhancement

#65 update to work without app rewriting
  files-override/.gitignore
  files-override/ember-cli-build.js
  files-override/testem.js
  files-override/tests/index.html
  files/vite.config.mjs
  index.js
Labels: enhancement

#68 update to user-controlled babel file
  files/babel.config.cjs
Labels: enhancement

#71 add a test for dev mode tests
  package.json
  pnpm-lock.yaml
  tests/default.test.mjs
  tests/fixture/testem-proxy.js
Labels: internal

#73 recreate issue with decorator transforms in tests and fix it
  files/babel.config.cjs
  index.js
  tests/fixture/app/routes/styles.js
Labels: bug

#70 fix: Uninstall task fails gracefully when given packages are not found
  index.js
Labels: bug

#81 Prepare for typescript support by moving all the js files into a js folder
  eslint.config.mjs
  files-override/js/.gitignore
  files-override/js/app/app.js
  files-override/js/ember-cli-build.js
  files-override/js/testem.js
  files-override/js/tests/index.html
  files-override/js/tests/test-helper.js
  files/js/app/config/environment.js
  files/js/babel.config.cjs
  files/js/index.html
  files/js/vite.config.mjs
  index.js
Labels: internal

#84 Run linting on the generated project in CI // add a working eslintconfig
  files-override/js/eslint.config.mjs
  index.js
  tests/default.test.mjs
Labels: internal

#83 Add prettier config (with `<template>` support
  files-override/shared/.prettierrc.cjs
  index.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#86 use the new load initializers and resolver
  files-override/js/app/app.js
  index.js
Labels: enhancement

#88 Use local ember-cli instead of global
  package.json
  pnpm-lock.yaml
  tests/default.test.mjs
  tests/helpers.mjs
Labels: internal
