Repository embroider-build/app-blueprint, pull requests merged in 2024-06, with the labels that each got.

#21 add docs for updating an existing app
  README.md
Labels: documentation

#30 docs: document update command
  README.md
Labels: documentation

#31 fix the location of the rewritten app
  files/vite.config.mjs
Labels: enhancement

#35 add notification for failed github action
  .github/workflows/ci.yml
Labels: internal

#37 add new app.js structure
  eslint.config.mjs
  files-override/app/app.js
  files-override/app/index.html
Labels: enhancement

#28 add regression tests for initialisers
  tests/default.test.mjs
  tests/fixture/app/initializers/test-init.js
  tests/fixture/app/instance-initializers/test-instance-init.js
  tests/fixture/tests/acceptance/app-init-test.js
Labels: internal
