Repository embroider-build/app-blueprint, pull requests merged in 2024-05, with the labels that each got.

#1 Initial working version
  .gitignore
  eslint.config.mjs
  files-override/app/index.html
  files-override/ember-cli-build.js
  files-override/tests/index.html
  files/babel.config.cjs
  files/vite.config.mjs
  index.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#2 setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#4 add ember-blueprint to keywords
  package.json
Labels: bug

#9 make sure ember-cli-update config is correct
  index.js
  lib/ember-cli-update.js
Labels: enhancement

#10 add a basic smoke test
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  tests/default.test.mjs
  vitest.config.ts
Labels: internal

#6 Remove unneeded deps
  index.js
Labels: enhancement

#11 docs: use npx instead of ember-cli global
  README.md
Labels: documentation

#14 add a dependabot config to keep ember-cli up to date
  .github/dependabot.yml
Labels: internal

#15 schedule CI to run once a day
  .github/workflows/ci.yml
Labels: internal

#17 Add smoke tests and fix the app-name.css link in index.html
  eslint.config.mjs
  files-override/app/index.html
  files-override/tests/index.html
  index.js
  lib/copy-with-template.js
  lib/ember-cli-update.js
  package.json
  pnpm-lock.yaml
  tests/default.test.mjs
  tests/fixture/app/router.js
  tests/fixture/app/styles/app.css
  tests/fixture/app/templates/application.hbs
  tests/fixture/app/templates/index.hbs
  tests/fixture/app/templates/styles.hbs
  tests/fixture/tests/acceptance/styles-test.js
  tests/fixture/tests/acceptance/welcome-page-test.js
Labels: bug

#18 add new config structure
  eslint.config.mjs
  files/app/config/environment.js
  index.js
Labels: enhancement
